# Generated by Django 4.2.6 on 2023-10-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_modelview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='text',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='title',
            new_name='name',
        ),
    ]
