# Generated by Django 4.2.6 on 2023-10-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Software Developer'), (2, 'QA Engineer'), (3, 'DevOps Specialist')]),
        ),
    ]
