# Generated by Django 4.2.6 on 2023-10-28 07:37

from django.db import migrations, models
import petstagram.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_petphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='', validators=[petstagram.main.validators.ValidateFileMaxSizeInMb]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], max_length=11, null=True),
        ),
    ]
